### ISSUE TITLE
Plugin Error in IDEA 2018.1

### ISSUE THREAD

**Issue by sunriseydy** [fangyuzhong2016/HadoopIntellijPlugin#3]
您好，在 IDEA 2018.1 中添加编译好的插件，重启后出现错误（刚启动 IDEA 的时候就出现错误，必须停用插件才能正常启动），错误日志如下：

```Plugin 'com.fangyuzhong.intelliJ.hadoop' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class com.fangyuzhong.intelliJ.hadoop.options.DefaultProjectSettingsManager]
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:75)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:155)
    at com.fangyuzhong.intelliJ.hadoop.options.DefaultProjectSettingsManager.getInstance(DefaultProjectSettingsManager.java:32)
    at com.fangyuzhong.intelliJ.hadoop.options.ProjectSettingsManager.getSettings(ProjectSettingsManager.java:46)
    at com.fangyuzhong.intelliJ.hadoop.options.ProjectSettings.<init>(ProjectSettings.java:48)
    at com.fangyuzhong.intelliJ.hadoop.options.DefaultProjectSettingsManager.<init>(DefaultProjectSettingsManager.java:27)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:68)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
请问如何解决这个问题，还是说目前插件只能用于 2017 版本的 IDEA ？

**Comment by fangyuzhong2016** [comment]
需要把源码下载下来，基于IDEA2018 重新编译,如果还是报错，可能就是插件本身的代码的问题（UI那块），需要调试了。插件是基于IDEA2017 开发测试的，没有在IDEA2018上运行过

**Comment by fangyuzhong2016** [comment]
需要把源码下载下来，基于IDEA2018 重新编译,如果还是报错，可能就是插件本身的代码的问题（UI那块），需要调试了。插件是基于IDEA2017 开发测试的，没有在IDEA2018上运行过
